PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX ldp: <http://www.w3.org/ns/ldp#>
PREFIX ejp: <http://purl.org/ejp-rd/vocabulary/>
PREFIX orphanet: <http://www.orpha.net/ORDO/Orphanet_>


SELECT DISTINCT ?catalogURI ?catalog ?registryURI ?registry ?country ?diseaseURI ?disease WHERE {

  VALUES(?country) {("#country#")} 
  VALUES(?diseaseInput) {(<#disease#>)}   
  VALUES(?registryType) {(<#registryType#>)}   
  
  ?diseaseURI  rdfs:subClassOf* ?diseaseInput.

  ?baseContainer ldp:contains ?catalogContainer .

  GRAPH ?catalogContainer {
    ?catalogURI a ejp:CatalogOfRegistries .
    ?catalogURI dct:title ?catalog .
    ?catalogURI dcat:dataset ?registryURI .
    ?catalogContainer ldp:contains ?registryContainer
  }
  GRAPH ?registryContainer {
    ?registryURI a ?registryType .
    ?registryURI dct:title ?registry .
    ?registryURI dcat:theme ?diseaseURI .
    ?registryURI dct:publisher [ dct:spatial [ ejp:country ?country] ]    

  }
  
  ?diseaseURI rdfs:label ?disease

}